#!/bin/bash

if [[ ! ( $# == 1 ) ]]; then
  echo "Usage: $0 properties_file"
  echo ""

  exit 1
fi;

export properties_file=$1

java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000 -cp camus-mate1-job/target/camus-mate1-job-0.1.0-kafka0.7.2-scala2.10.3-SNAPSHOT-shaded.jar:/usr/lib/hadoop-hdfs/hadoop-hdfs.jar:log4j.properties com.linkedin.camus.etl.kafka.CamusJob -P $properties_file

#java -cp camus-mate1-job/target/camus-mate1-job-0.1.0-kafka0.7.2-scala2.10.3-SNAPSHOT-shaded.jar:/etc/hadoop/conf:/usr/lib/hadoop-hdfs/hadoop-hdfs.jar:log4j.properties com.linkedin.camus.etl.kafka.CamusJob -P $properties_file
